module.exports = {
	quotes: [
		'People are gonna get triggered if you think like that!',
		'Um...',
		'This is awkward.',
		'I\'ve learned my lesson now, OK.',
		'I\'m gonna pretend he\'s going to University to be an orthopedic surgeon. Look it up.',
		'He\'s a genuinely great guy',
		'Yes, my good sir. I\'ll have the milk steak, boiled over hard, and your finest jelly beans. Raw.',
		'I don\'t like the concept of Wikipedia. People can just hop on and, like, write whatever they feel like. And people will accept it as fact!',
		'Stab me?',
		'Stop! You\'re freaking me out!',
		'We both live in the oven that is Arizona.',
		'What kind of argument is that?',
		'I hope all the braeburn trees braeBURN in a giant fire and rebirth into Pacific Rose ones.',
		'ENJOY YOURSELVES!!!!!!',
		'Happy Christmahanikwansa',
		'SONIC MODE FREAKING ENGAGED!!',
		'Aw, fish-frick!',
		'Just because you know you\'re color blind, doesn\'t mean you can see the colors.',
		'Sugoi!',
		'None of these REVOLTING pieces of literature hold a candle to the masterpiece... Leave it to Pet, The Misadventures of a Recycled Super Robot.',
		'Oh... um... HI!',
		'Kids are incompetent at life.',
		'Hello stranger with a degree, I\'m here to tell you why I\'m broken!',
		'Instead of shaking hands, how about we do finger guns? See! Easier for everybody!',
		'They\'re allowing a child to go in an active volcano.',
		'We have some Asain blood in us, so we can\'t bring dishonor to the family.',
		'It\'s simple, just don\'t be stupid',
		'Wind is my least favorite weather! People with long hair can understand…',
		'If you can\'t help yourself, help others. Then eventually, you might be able to learn how to help yourself, too.',
		'I\'ll be personally offended if you don\'t let me play with your pet for at least 2 hours.',
		'What’s in that forest, Logan?',
		'I\'M GAYYYY!!!!!!',
		'Oh, hello Shroomish. I\'m going to name you Onion.',
		'Oh yeah. I know what your name is.',
		'You can\'t stand me up like that! At least give me some sort of reason!',
		'Come on, Come back! Rajesh!',
		'I\'m gonna name you Chad. Oh, you\'re a girl? Did I stutter?',
		'I\'m not crying. Someone\'s just chopping Onions here.',
		'ARE YOU NAKED?!?!',
		'Don\'t ever die',
		'Spend time with friends! (If you have any)',
		'PEE IS STORED IN TH-',
		'Use protection.',
		'y\'all simps',
		'Everyone who\'s watching, if you\'re young, take your time right now, your free time... because you won\'t have free time in the future.',
		'STOP!! You\'re freaking me out!',
		'If you knowing I\'m hurt, hurts you then I dont wanna tell you when I\'m hurting.',
		'I was just recording a video with a bunch of friends and I got a Twitter notification, and in the middle of conversation I went: "Holy-!", a-and then I swore',
		'Calm down drink a cup of water or something',
		'Everyone\'s so quick to just hate each other now',
		'It\'s not edgy to be edgy anymore',
		'Just because this person is being scummy, doesn\'t mean you can automatically be scummy back to them that\'s that\'s not at all how it works',
		'He\'s gay.'
	]
};
